const Map<String, String> areasMap = {
  'American': 'US',
  'British': 'GB',
  'Canadian': 'CA',
  'Chinese': 'CN',
  'Croatian': 'HR',
  'Dutch': 'DE',
  'Egyptian': 'EG',
  'Filipino': 'PH',
  'French': 'FR',
  'Greek': 'GR',
  'Indian': 'IN',
  'Irish': 'IE',
  'Italian': 'IT',
  'Jamaican': 'JM',
  'Japanese': 'JP',
  'Kenyan': 'KE',
  'Malaysian': 'MY',
  'Mexican': 'MX',
  'Moroccan': 'MA',
  'Polish': 'PL',
  'Portuguese': 'PT',
  'Russian': 'RU',
  'Spanish': 'ES',
  'Thai': 'TH',
  'Tunisian': 'TN',
  'Turkish': 'TR',
  'Vietnamese': 'VN',
  'Unknown': 'Unknown', // Uncomment if 'Unknown' is a valid country code
};
